config/routes.rb
Rails.application.routes.draw do
  resources :lectures do
    resources :tasks
  end
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :lecture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  def index
    @lectures = Lecture.all
  end

  def new
    @lecture = Lecture.new
  end

  def create
    @lecture = Lecture.new(lecture_params)
    if @lecture.save
      redirect_to lectures_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def lecture_params
    params.require(:lecture).permit(:name, :body)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_lecture

  def index
    @tasks = @lecture.tasks
  end

  # POST /lectures/1/tasks/new
  def new
    @task = Task.new
  end

  # POST /lectures/1/tasks
  def create
    @task = @lecture.tasks.build(task_params)
    if @task.save
      redirect_to lecture_tasks_path(params[:lecture_id])
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PUT /lectures/1/tasks/new
  def edit
    @task = @lecture.tasks.find(params[:id])
  end

  def update
    @task = @lecture.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to lecture_tasks_path(params[:lecture_id])
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :description)
  end

  def set_lecture
    @lecture = Lecture.find(params[:lecture_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_helper.rb
module MyHelper
  def sup_holmie
    "<p>Sup' HOLMIE!!!</p>".html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Course</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lectures/index.html.erb
<h2>Lectures</h2>

<ul>
	<% @lectures.each do |lecture| %>
		<li><%= lecture.inspect %></li>
	<% end %>
</ul>

<%= link_to "Create Lecture", new_lecture_path %>

app/views/lectures/new.html.erb
<h2>Create Lecture</h2>

<%= form_for(@lecture) do |f| %>
	<%= f.label :name %> <%= f.text_field :name %>
	<%= f.label :body %> <%= f.text_area :body %>

	<%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<%= f.label :name %> <%= f.text_field :name %>
<%= f.label :description %> <%= f.text_area :description %>

<%= f.submit %>

app/views/tasks/edit.html.erb
<h2>Edit Task</h2>

<%= form_for @task, method: :patch, url: lecture_task_path(@lecture, @task) do |f| %>
	<%= render @task, f: f %>
<% end %>

app/views/tasks/index.html.erb
<h2>Tasks</h2>

<ul>
	<% @tasks.each do |task| %>
		<li><%= task.inspect %></li>
	<% end %>
</ul>

<%= link_to "Create Task", new_lecture_task_path(@lecture) %>

app/views/tasks/new.html.erb
<h2>Create Task</h2>

<%= form_for(@task, url: lecture_tasks_path(@lecture)) do |f| %>
	<%= render @task, f: f %>
<% end %>